encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge


# 作者信息
author: 
  name: 王启
  email: nwpu_wq@163.com
  link: https://wongkee.github.io
  github: https://github.com/wongkee
  github_username:  wongkee

# 站点信息
title : Rudolf's Home
description: 
  计算机专业在读研究生，主要对云计算、分布式比较感兴趣，热爱读史书、交朋友。
url: https://wongkee.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : DarLie<br>Java Developer<br>

# 首页除了最新文章外显示分类
cates: 
- Essay

# 中文本地化
locals: 
   newest : 最新文章